# Generated by Django 3.1.2 on 2021-04-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.PositiveBigIntegerField(default=91)),
                ('email', models.EmailField(default='gmail.com', max_length=254)),
                ('linkedin', models.URLField(default='www.linkedin.com/')),
                ('password', models.TextField(default='******')),
            ],
        ),
    ]
